import { CardId } from '@/game-data/card';
import { ItemKey, type CardSkinItemKey } from '@/game-data/item-key';
import { Resource } from '@/game/resource';

export const CardSkinToResource: Record<CardSkinItemKey, string> = {
  [ItemKey.CardSkinGoldenSpecial]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenLabradoodle]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenDobermann]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenHusky]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenRetriever]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenCorgi]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenPug]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenDoxie]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenYork]: Resource.Card.Skin.Golden,
  [ItemKey.CardSkinGoldenSpitz]: Resource.Card.Skin.Golden,
};

export const CardIdToCardSkins: { [id in CardId]?: CardSkinItemKey[] } = {
  [CardId.Nature1]: [ItemKey.CardSkinGoldenSpitz],
  [CardId.Nature2]: [ItemKey.CardSkinGoldenYork],
  [CardId.Nature3]: [ItemKey.CardSkinGoldenDoxie],
  [CardId.Nature4]: [ItemKey.CardSkinGoldenPug],
  [CardId.Nature5]: [ItemKey.CardSkinGoldenCorgi],
  [CardId.Nature6]: [ItemKey.CardSkinGoldenRetriever],
  [CardId.Nature7]: [ItemKey.CardSkinGoldenHusky],
  [CardId.Nature8]: [ItemKey.CardSkinGoldenDobermann],
  [CardId.Nature9]: [ItemKey.CardSkinGoldenLabradoodle],
  [CardId.NatureHydrant]: [ItemKey.CardSkinGoldenSpecial],
  // [CardId.NatureSoundboard]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.NatureTrashCanDiving]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.NatureShaking]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.NatureTreatHiding]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.Filth1]: [ItemKey.CardSkinGoldenSpitz],
  [CardId.Filth2]: [ItemKey.CardSkinGoldenYork],
  [CardId.Filth3]: [ItemKey.CardSkinGoldenDoxie],
  [CardId.Filth4]: [ItemKey.CardSkinGoldenPug],
  [CardId.Filth5]: [ItemKey.CardSkinGoldenCorgi],
  [CardId.Filth6]: [ItemKey.CardSkinGoldenRetriever],
  [CardId.Filth7]: [ItemKey.CardSkinGoldenHusky],
  [CardId.Filth8]: [ItemKey.CardSkinGoldenDobermann],
  [CardId.Filth9]: [ItemKey.CardSkinGoldenLabradoodle],
  [CardId.FilthHydrant]: [ItemKey.CardSkinGoldenSpecial],
  // [CardId.FilthSoundboard]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.FilthTrashCanDiving]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.FilthShaking]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.FilthTreatHiding]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.Arcane1]: [ItemKey.CardSkinGoldenSpitz],
  [CardId.Arcane2]: [ItemKey.CardSkinGoldenYork],
  [CardId.Arcane3]: [ItemKey.CardSkinGoldenDoxie],
  [CardId.Arcane4]: [ItemKey.CardSkinGoldenPug],
  [CardId.Arcane5]: [ItemKey.CardSkinGoldenCorgi],
  [CardId.Arcane6]: [ItemKey.CardSkinGoldenRetriever],
  [CardId.Arcane7]: [ItemKey.CardSkinGoldenHusky],
  [CardId.Arcane8]: [ItemKey.CardSkinGoldenDobermann],
  [CardId.Arcane9]: [ItemKey.CardSkinGoldenLabradoodle],
  [CardId.ArcaneHydrant]: [ItemKey.CardSkinGoldenSpecial],
  // [CardId.ArcaneSoundboard]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.ArcaneTrashCanDiving]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.ArcaneShaking]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.ArcaneTreatHiding]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.Multimatter]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfFortune]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfFate]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfCurse]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfLuck]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfWisdom]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfWish]: [ItemKey.CardSkinGoldenSpecial],
};
