import { Module } from '@kwokka/common-node';
import {
  DecorationMongoRepository,
  DecorationV1Controller,
  DecorationV1Router,
  ItemInstanceMongoRepository,
  ItemInstanceV1Controller,
  ItemMongoRepository,
  ItemTradeMongoRepository,
  ItemTradeV1Controller,
  ItemTradeV1Router,
  ItemTransactionMongoRepository,
  ItemV1Controller,
  ItemV1Router,
  ProfileDecorationsMongoRepository,
  ProfileDecorationsV1Controller,
  ProfileDecorationsV1Router,
  ProfileMongoRepository,
  ProfileV1Controller,
  ProfileV1Router,
  RootRouter,
  TraitInstanceMongoRepository,
  TraitInstanceV1Controller,
  TraitMongoRepository,
  TraitV1Controller,
  TraitV1Router,
  V1RootRouter,
} from '../application';
import {
  CreateDecorationUsecase,
  CreateItemTradeUsecase,
  CreateItemTransactionUsecase,
  CreateItemUsecase,
  CreateProfileDecorationsUsecase,
  CreateProfileUsecase,
  CreateTraitUsecase,
  DecorationRepository,
  DeleteDecorationUsecase,
  DeleteItemTradeUsecase,
  DeleteItemUsecase,
  DeleteProfileDecorationsUsecase,
  DeleteProfileUsecase,
  DeleteTraitInstanceUsecase,
  DeleteTraitUsecase,
  GetDecorationByIdUsecase,
  GetDecorationByKeyUsecase,
  GetItemByIdUsecase,
  GetItemByKeyUsecase,
  GetItemInstanceByIdUsecase,
  GetItemInstanceByItemIdUsecase,
  GetItemInstanceByItemKeyUsecase,
  GetItemTradeByIdUsecase,
  GetItemTradeByKeyUsecase,
  GetProfileByAccountIdUsecase,
  GetProfileByIdUsecase,
  GetProfileDecorationsByProfileIdUsecase,
  GetTraitByIdUsecase,
  GetTraitByKeyUsecase,
  GetTraitInstanceUsecase,
  GiveItemInstanceByItemKeyUsecase,
  GiveItemInstanceUsecase,
  ItemInstanceRepository,
  ItemRepository,
  ItemTradeRepository,
  ItemTransactionRepository,
  ListAvailableDecorationsUsecase,
  ListDecorationsUsecase,
  ListItemInstancesUsecase,
  ListItemsUsecase,
  ListItemTradesUsecase,
  ListProfilesUsecase,
  ListTraitInstancesUsecase,
  ListTraitsUsecase,
  ProfileDecorationsRepository,
  ProfileRepository,
  RunItemInstanceActionByItemIdUsecase,
  RunItemInstanceActionByItemKeyUsecase,
  RunItemInstanceActionUsecase,
  RunItemTradeUsecase,
  TakeItemInstanceByItemKeyUsecase,
  TakeItemInstanceUsecase,
  TraitInstanceRepository,
  TraitRepository,
  UpdateDecorationUsecase,
  UpdateItemTradeUsecase,
  UpdateItemUsecase,
  UpdateProfileDecorationsUsecase,
  UpdateProfileUsecase,
  UpdateTraitInstanceUsecase,
  UpdateTraitUsecase,
} from '../usecase';

export class CapybaraModule extends Module {
  public get components() {
    return [
      // usecase/ports
      { identifier: ProfileRepository, implementer: ProfileMongoRepository },
      { identifier: DecorationRepository, implementer: DecorationMongoRepository },
      { identifier: ItemInstanceRepository, implementer: ItemInstanceMongoRepository },
      { identifier: ItemTradeRepository, implementer: ItemTradeMongoRepository },
      { identifier: ItemTransactionRepository, implementer: ItemTransactionMongoRepository },
      { identifier: ItemRepository, implementer: ItemMongoRepository },
      { identifier: ProfileDecorationsRepository, implementer: ProfileDecorationsMongoRepository },
      { identifier: TraitRepository, implementer: TraitMongoRepository },
      { identifier: TraitInstanceRepository, implementer: TraitInstanceMongoRepository },

      // application/router
      RootRouter,
      V1RootRouter,
      DecorationV1Router,
      ProfileV1Router,
      ProfileDecorationsV1Router,
      ItemV1Router,
      ItemTradeV1Router,
      TraitV1Router,

      // application/controller
      ProfileV1Controller,
      DecorationV1Controller,
      ProfileDecorationsV1Controller,
      ItemV1Controller,
      ItemTradeV1Controller,
      ItemInstanceV1Controller,
      TraitV1Controller,
      TraitInstanceV1Controller,

      // usecase/profile
      ListProfilesUsecase,
      CreateProfileUsecase,
      UpdateProfileUsecase,
      GetProfileByIdUsecase,
      GetProfileByAccountIdUsecase,
      DeleteProfileUsecase,

      // usecase/decoration
      CreateDecorationUsecase,
      DeleteDecorationUsecase,
      GetDecorationByIdUsecase,
      ListDecorationsUsecase,
      UpdateDecorationUsecase,
      GetDecorationByKeyUsecase,
      ListAvailableDecorationsUsecase,

      // usecase/profile-decorations
      UpdateProfileDecorationsUsecase,
      GetProfileDecorationsByProfileIdUsecase,
      DeleteProfileDecorationsUsecase,
      CreateProfileDecorationsUsecase,

      // usecase/item-instance
      TakeItemInstanceUsecase,
      ListItemInstancesUsecase,
      GiveItemInstanceUsecase,
      RunItemInstanceActionUsecase,
      RunItemInstanceActionByItemIdUsecase,
      RunItemInstanceActionByItemKeyUsecase,
      GetItemInstanceByIdUsecase,
      GetItemInstanceByItemIdUsecase,
      GetItemInstanceByItemKeyUsecase,
      GiveItemInstanceByItemKeyUsecase,
      TakeItemInstanceByItemKeyUsecase,

      // usecase/item-trade
      CreateItemTradeUsecase,
      DeleteItemTradeUsecase,
      GetItemTradeByIdUsecase,
      GetItemTradeByKeyUsecase,
      ListItemTradesUsecase,
      UpdateItemTradeUsecase,
      RunItemTradeUsecase,

      // usecase/item-transaction
      CreateItemTransactionUsecase,

      // usecase/item
      UpdateItemUsecase,
      ListItemsUsecase,
      GetItemByIdUsecase,
      DeleteItemUsecase,
      CreateItemUsecase,
      GetItemByKeyUsecase,

      // usecase/trait
      CreateTraitUsecase,
      DeleteTraitUsecase,
      GetTraitByIdUsecase,
      GetTraitByKeyUsecase,
      ListTraitsUsecase,
      UpdateTraitUsecase,

      // usecase/trait-instance
      GetTraitInstanceUsecase,
      DeleteTraitInstanceUsecase,
      ListTraitInstancesUsecase,
      UpdateTraitInstanceUsecase,
    ];
  }
}
