import type { KwokkaSoundConfig } from '@kwokka/sound';

export enum SoundGroup {
  Music = 'music',
  Sfx = 'sfx',
  Voice = 'voice',
}

export enum SoundId {
  Bubbles = 'bubbles',
  BubblePop = 'bubble_pop',
  MagicOverlay = 'magic_overlay',
  CardDraw1 = 'card_draw_1',
  CardEffectApply = 'card_effect_apply',
  CardPlay1 = 'card_play_1',
  CardPlay2 = 'card_play_2',
  CardPlayFail1 = 'card_play_fail_1',
  GameEndLoop = 'game_end_loop',
  GameEnd = 'game_end',
  GameStart1 = 'game_start_1',
  GameStart2 = 'game_start_2',
  GameTheme1 = 'game_theme_1',
  GameTheme2 = 'game_theme_2',
  GameTheme3 = 'game_theme_3',
  GameTheme4 = 'game_theme_4',
  GameTheme5 = 'game_theme_5',
  GameTheme6 = 'game_theme_6',
  GameTheme7 = 'game_theme_7',
  MainMenuTheme1 = 'main_menu_theme_1',
  MainMenuTheme2 = 'main_menu_theme_2',
  MainMenuTheme3 = 'main_menu_theme_3',
  PlayerRoomJoin1 = 'player_room_join_1',
  PlayerRoomJoin2 = 'player_room_join_2',
  PlayerRoomLeave1 = 'player_room_leave_1',
  SkillEquip = 'skil_equip',
  SkillPlay1 = 'skill_play_1',
  SkillPlay2 = 'skill_play_2',
  SkillPlay3 = 'skill_play_3',
  SkillPlay4 = 'skill_play_4',
  SkillUnlock = 'skill_unlock',
  UiFail = 'ui_fail',
  UiHover1 = 'ui_hover_1',
  UiSelect1 = 'ui_select_1',
  UiSelect2 = 'ui_select_2',
  VoiceNarratorNeutral1 = 'voice_narrator_neutral_1',
  VoiceNarratorNeutral2 = 'voice_narrator_neutral_2',
  VoiceNarratorNeutral3 = 'voice_narrator_neutral_3',
  VoiceNarratorNeutral4 = 'voice_narrator_neutral_4',
  VoiceNarratorNeutral5 = 'voice_narrator_neutral_5',
  VoiceNarratorNeutral8 = 'voice_narrator_neutral_8',
  VoiceNarratorNeutral13 = 'voice_narrator_neutral_13',
  VoiceNarratorQuestion1 = 'voice_narrator_question_1',
  VoiceNarratorQuestion2 = 'voice_narrator_question_2',
  VoiceNarratorQuestion3 = 'voice_narrator_question_3',
  VoiceNarratorExclamation2 = 'voice_narrator_exclamation_2',
  VoiceNarratorExclamation3 = 'voice_narrator_exclamation_3',
  VoiceNarratorExclamation5 = 'voice_narrator_exclamation_5',
  VoiceNarratorMystery1 = 'voice_narrator_mystery_1',
  VoiceNarratorMystery3 = 'voice_narrator_mystery_3',
  VoiceNarratorMystery4 = 'voice_narrator_mystery_4',
  BookPage1 = 'book_page_1',
  BookPage2 = 'book_page_2',
  BookOpen = 'book_open',
  BookClose = 'book_close',
}

export const SoundConfig: KwokkaSoundConfig = {
  sfx: [
    // Music

    {
      id: SoundId.MainMenuTheme1,
      group: SoundGroup.Music,
      src: '/static/music/main_1.mp3',
      preload: true,
      gain: 0.4,
      suspend: true,
    },
    {
      id: SoundId.MainMenuTheme2,
      group: SoundGroup.Music,
      src: '/static/music/main_2.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.MainMenuTheme3,
      group: SoundGroup.Music,
      src: '/static/music/main_3.mp3',
      preload: true,
      gain: 0.8,
      suspend: true,
    },
    {
      id: SoundId.GameTheme1,
      group: SoundGroup.Music,
      src: '/static/music/game_1.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameTheme2,
      group: SoundGroup.Music,
      src: '/static/music/game_2.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameTheme3,
      group: SoundGroup.Music,
      src: '/static/music/game_3.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameTheme4,
      group: SoundGroup.Music,
      src: '/static/music/game_4.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameTheme5,
      group: SoundGroup.Music,
      src: '/static/music/game_5.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameTheme6,
      group: SoundGroup.Music,
      src: '/static/music/game_6.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameTheme7,
      group: SoundGroup.Music,
      src: '/static/music/game_7.mp3',
      preload: true,
      gain: 1,
      suspend: true,
    },
    {
      id: SoundId.GameEndLoop,
      group: SoundGroup.Music,
      src: '/static/music/end_game_loop.mp3',
      preload: true,
      gain: 0.25,
      loop: true,
      suspend: true,
    },

    // SFX/UI

    {
      id: SoundId.UiHover1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/ui_hover_1.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.UiSelect1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/ui_select_1.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.UiSelect2,
      group: SoundGroup.Sfx,
      src: '/static/sfx/ui_select_2.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.PlayerRoomJoin1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_bottle_1.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.PlayerRoomJoin2,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_bottle_2.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.PlayerRoomLeave1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/chest.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },

    // SFX/Game

    {
      id: SoundId.CardDraw1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/card_draw_1.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.CardPlay1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/card_play_1.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.CardPlay2,
      group: SoundGroup.Sfx,
      src: '/static/sfx/card_play_2.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.Bubbles,
      group: SoundGroup.Sfx,
      src: '/static/sfx/bubbles.mp3',
      preload: true,
      gain: 1.4,
      suspend: false,
    },
    {
      id: SoundId.BubblePop,
      group: SoundGroup.Sfx,
      src: '/static/sfx/bubble_pop.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.UiFail,
      group: SoundGroup.Sfx,
      src: '/static/sfx/ui_fail.mp3',
      preload: true,
      gain: 1.2,
      suspend: false,
    },
    {
      id: SoundId.GameStart1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/peak_1.mp3',
      preload: true,
      gain: 0.5,
      suspend: false,
    },
    {
      id: SoundId.GameStart2,
      group: SoundGroup.Sfx,
      src: '/static/sfx/peak_2.mp3',
      preload: true,
      gain: 1,
      suspend: false,
    },
    {
      id: SoundId.GameEnd,
      group: SoundGroup.Sfx,
      src: '/static/sfx/gate_lock.mp3',
      preload: true,
      gain: 1.15,
      suspend: false,
    },
    {
      id: SoundId.CardEffectApply,
      group: SoundGroup.Sfx,
      src: '/static/sfx/card_effect_apply.mp3',
      preload: true,
      gain: 0.7,
      suspend: false,
    },
    {
      id: SoundId.CardPlayFail1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/card_play_fail_1.mp3',
      preload: true,
      gain: 0.7,
      suspend: false,
    },
    {
      id: SoundId.MagicOverlay,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_pop_2.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.SkillEquip,
      group: SoundGroup.Sfx,
      src: '/static/sfx/fire_select.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.SkillPlay1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_poof_1.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.SkillPlay2,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_poof_2.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.SkillPlay3,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_poof_3.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.SkillPlay4,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_poof_4.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.SkillUnlock,
      group: SoundGroup.Sfx,
      src: '/static/sfx/magic_pop_1.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.VoiceNarratorNeutral1,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_1.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorNeutral2,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_2.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorNeutral3,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_3.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorNeutral4,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_4.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorNeutral5,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_5.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorNeutral8,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_8.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorNeutral13,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_neutral_13.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorExclamation2,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_exclamation_2.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorExclamation3,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_exclamation_3.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorExclamation5,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_exclamation_5.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorMystery1,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_mystery_1.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorMystery3,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_mystery_3.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorMystery4,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_mystery_4.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorQuestion1,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_question_1.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorQuestion2,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_question_2.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.VoiceNarratorQuestion3,
      group: SoundGroup.Voice,
      src: '/static/voice/voice_question_3.mp3',
      preload: true,
      suspend: false,
      gain: 4,
    },
    {
      id: SoundId.BookPage1,
      group: SoundGroup.Sfx,
      src: '/static/sfx/page_turn_1.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.BookPage2,
      group: SoundGroup.Sfx,
      src: '/static/sfx/page_turn_2.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.BookOpen,
      group: SoundGroup.Sfx,
      src: '/static/sfx/book_open.mp3',
      preload: true,
      suspend: false,
    },
    {
      id: SoundId.BookClose,
      group: SoundGroup.Sfx,
      src: '/static/sfx/book_close.mp3',
      preload: true,
      suspend: false,
    },
  ],
};
