import { CardId, CardType, CardElement, CardSet } from './card';
import { PawsomeElementsConfigInterface } from './config-interface';

export const PawsomeElementsConfig: PawsomeElementsConfigInterface = {
  turnDuration: 30 * 1000,
  hydrantMaxDuration: 10 * 1000,
  soundboardMaxDuration: 10 * 1000,
  tambourineMaxDuration: 10 * 1000,
  peacePipeMaxDuration: 10 * 1000,
  fireTotemMaxDuration: 10 * 1000,
  waterTotemMaxDuration: 10 * 1000,
  spiritTotemMaxDuration: 10 * 1000,
  lesserRitualMaxDuration: 10 * 1000,
  ballOfFortuneMaxDuration: 10 * 1000,
  skillCooldownTurns: 3,
  startCardsCount: 5,
  firstTurnDuration: 60 * 1000,
  botMinTurnDurationMultiplier: 0.04,
  botMaxTurnDurationMultiplier: 0.07,
  botMinOutOfTurnDurationMultiplier: 0.05,
  botMaxOutOfTurnDurationMultiplier: 0.08,
  botMinInteractionDurationMultiplier: 0.3,
  botMaxInteractionDurationMultiplier: 0.7,
  botRandomDelayChance: 0.03,
  botSpellUseChance: 0.65,
  cards: {
    // SERVICE CARDS

    [CardId.Placeholder]: { type: CardType.Common, element: CardElement.Multimatter, power: -1 },

    // STANDARD SET

    [CardId.Nature1]: { type: CardType.Common, element: CardElement.Nature, power: 1 },
    [CardId.Nature2]: { type: CardType.Common, element: CardElement.Nature, power: 2 },
    [CardId.Nature3]: { type: CardType.Common, element: CardElement.Nature, power: 3 },
    [CardId.Nature4]: { type: CardType.Common, element: CardElement.Nature, power: 4 },
    [CardId.Nature5]: { type: CardType.Common, element: CardElement.Nature, power: 5 },
    [CardId.Nature6]: { type: CardType.Common, element: CardElement.Nature, power: 6 },
    [CardId.Nature7]: { type: CardType.Common, element: CardElement.Nature, power: 7 },
    [CardId.Nature8]: { type: CardType.Common, element: CardElement.Nature, power: 8 },
    [CardId.Nature9]: { type: CardType.Common, element: CardElement.Nature, power: 9 },
    [CardId.NatureTrashCanDiving]: { type: CardType.Special, element: CardElement.Nature, power: 100 },
    [CardId.NatureShaking]: { type: CardType.Special, element: CardElement.Nature, power: 101 },
    [CardId.NatureTreatHiding]: { type: CardType.Special, element: CardElement.Nature, power: 102 },
    [CardId.NatureHydrant]: { type: CardType.Special, element: CardElement.Nature, power: 1000 },
    // [CardId.NatureSoundboard]: { type: CardType.Special, element: CardElement.Nature, power: 1001 },

    [CardId.Filth1]: { type: CardType.Common, element: CardElement.Filth, power: 1 },
    [CardId.Filth2]: { type: CardType.Common, element: CardElement.Filth, power: 2 },
    [CardId.Filth3]: { type: CardType.Common, element: CardElement.Filth, power: 3 },
    [CardId.Filth4]: { type: CardType.Common, element: CardElement.Filth, power: 4 },
    [CardId.Filth5]: { type: CardType.Common, element: CardElement.Filth, power: 5 },
    [CardId.Filth6]: { type: CardType.Common, element: CardElement.Filth, power: 6 },
    [CardId.Filth7]: { type: CardType.Common, element: CardElement.Filth, power: 7 },
    [CardId.Filth8]: { type: CardType.Common, element: CardElement.Filth, power: 8 },
    [CardId.Filth9]: { type: CardType.Common, element: CardElement.Filth, power: 9 },
    [CardId.FilthTrashCanDiving]: { type: CardType.Special, element: CardElement.Filth, power: 100 },
    [CardId.FilthShaking]: { type: CardType.Special, element: CardElement.Filth, power: 101 },
    [CardId.FilthTreatHiding]: { type: CardType.Special, element: CardElement.Filth, power: 102 },
    [CardId.FilthHydrant]: { type: CardType.Special, element: CardElement.Filth, power: 1000 },
    // [CardId.FilthSoundboard]: { type: CardType.Special, element: CardElement.Filth, power: 1001 },

    [CardId.Arcane1]: { type: CardType.Common, element: CardElement.Arcane, power: 1 },
    [CardId.Arcane2]: { type: CardType.Common, element: CardElement.Arcane, power: 2 },
    [CardId.Arcane3]: { type: CardType.Common, element: CardElement.Arcane, power: 3 },
    [CardId.Arcane4]: { type: CardType.Common, element: CardElement.Arcane, power: 4 },
    [CardId.Arcane5]: { type: CardType.Common, element: CardElement.Arcane, power: 5 },
    [CardId.Arcane6]: { type: CardType.Common, element: CardElement.Arcane, power: 6 },
    [CardId.Arcane7]: { type: CardType.Common, element: CardElement.Arcane, power: 7 },
    [CardId.Arcane8]: { type: CardType.Common, element: CardElement.Arcane, power: 8 },
    [CardId.Arcane9]: { type: CardType.Common, element: CardElement.Arcane, power: 9 },
    [CardId.ArcaneTrashCanDiving]: { type: CardType.Special, element: CardElement.Arcane, power: 100 },
    [CardId.ArcaneShaking]: { type: CardType.Special, element: CardElement.Arcane, power: 101 },
    [CardId.ArcaneTreatHiding]: { type: CardType.Special, element: CardElement.Arcane, power: 102 },
    [CardId.ArcaneHydrant]: { type: CardType.Special, element: CardElement.Arcane, power: 1000 },
    // [CardId.ArcaneSoundboard]: { type: CardType.Special, element: CardElement.Arcane, power: 1001 },
    [CardId.Multimatter]: { type: CardType.Special, element: CardElement.Multimatter, power: 0 },
    [CardId.BallOfFortune]: { type: CardType.Interaction, element: CardElement.Multimatter, power: 1002 },
    [CardId.BallOfCurse]: { type: CardType.Special, element: CardElement.Multimatter, power: 111 },
    [CardId.BallOfFate]: { type: CardType.Special, element: CardElement.Multimatter, power: 112 },
    [CardId.BallOfLuck]: { type: CardType.Special, element: CardElement.Multimatter, power: 113 },
    [CardId.BallOfWisdom]: { type: CardType.Special, element: CardElement.Multimatter, power: 114 },
    [CardId.BallOfWish]: { type: CardType.Special, element: CardElement.Multimatter, power: 115 },
  },

  cardSets: {
    [CardSet.Standard]: {
      [CardId.Nature1]: { count: 2 },
      [CardId.Nature2]: { count: 2 },
      [CardId.Nature3]: { count: 2 },
      [CardId.Nature4]: { count: 2 },
      [CardId.Nature5]: { count: 2 },
      [CardId.Nature6]: { count: 2 },
      [CardId.Nature7]: { count: 2 },
      [CardId.Nature8]: { count: 2 },
      [CardId.Nature9]: { count: 2 },
      [CardId.NatureHydrant]: { count: 1 },
      // [CardId.NatureSoundboard]: { count: 1 },
      [CardId.NatureTrashCanDiving]: { count: 1 },
      [CardId.NatureShaking]: { count: 1 },
      [CardId.NatureTreatHiding]: { count: 2 },

      [CardId.Filth1]: { count: 2 },
      [CardId.Filth2]: { count: 2 },
      [CardId.Filth3]: { count: 2 },
      [CardId.Filth4]: { count: 2 },
      [CardId.Filth5]: { count: 2 },
      [CardId.Filth6]: { count: 2 },
      [CardId.Filth7]: { count: 2 },
      [CardId.Filth8]: { count: 2 },
      [CardId.Filth9]: { count: 2 },
      [CardId.FilthHydrant]: { count: 1 },
      // [CardId.FilthSoundboard]: { count: 1 },
      [CardId.FilthTrashCanDiving]: { count: 1 },
      [CardId.FilthShaking]: { count: 1 },
      [CardId.FilthTreatHiding]: { count: 2 },

      [CardId.Arcane1]: { count: 2 },
      [CardId.Arcane2]: { count: 2 },
      [CardId.Arcane3]: { count: 2 },
      [CardId.Arcane4]: { count: 2 },
      [CardId.Arcane5]: { count: 2 },
      [CardId.Arcane6]: { count: 2 },
      [CardId.Arcane7]: { count: 2 },
      [CardId.Arcane8]: { count: 2 },
      [CardId.Arcane9]: { count: 2 },
      [CardId.ArcaneHydrant]: { count: 1 },
      // [CardId.ArcaneSoundboard]: { count: 1 },
      [CardId.ArcaneTrashCanDiving]: { count: 1 },
      [CardId.ArcaneShaking]: { count: 1 },
      [CardId.ArcaneTreatHiding]: { count: 2 },

      [CardId.Multimatter]: { count: 4 },
      [CardId.BallOfFortune]: { count: 4 },
    },
    [CardSet.Turbo]: {
      [CardId.Nature1]: { count: 2 },
      [CardId.Nature2]: { count: 2 },
      [CardId.Nature3]: { count: 2 },
      [CardId.Nature4]: { count: 2 },
      [CardId.Nature5]: { count: 2 },
      [CardId.NatureHydrant]: { count: 1 },
      [CardId.NatureTrashCanDiving]: { count: 1 },
      [CardId.NatureShaking]: { count: 1 },
      [CardId.NatureTreatHiding]: { count: 2 },

      [CardId.Filth1]: { count: 2 },
      [CardId.Filth2]: { count: 2 },
      [CardId.Filth3]: { count: 2 },
      [CardId.Filth4]: { count: 2 },
      [CardId.Filth5]: { count: 2 },
      [CardId.FilthHydrant]: { count: 1 },
      [CardId.FilthTrashCanDiving]: { count: 1 },
      [CardId.FilthShaking]: { count: 1 },
      [CardId.FilthTreatHiding]: { count: 2 },

      [CardId.Arcane1]: { count: 2 },
      [CardId.Arcane2]: { count: 2 },
      [CardId.Arcane3]: { count: 2 },
      [CardId.Arcane4]: { count: 2 },
      [CardId.Arcane5]: { count: 2 },
      [CardId.ArcaneHydrant]: { count: 1 },
      [CardId.ArcaneTrashCanDiving]: { count: 1 },
      [CardId.ArcaneShaking]: { count: 1 },
      [CardId.ArcaneTreatHiding]: { count: 2 },

      [CardId.Multimatter]: { count: 4 },
      [CardId.BallOfFortune]: { count: 4 },
    },
  },
};
