export enum EventKey {
  Resize = 'resize',
  SetState = 'set_state',
  SetConfig = 'set_config',
  SetTurnDuration = 'set_turn_duration',
  SetTranslations = 'set_translations',
  SetConnectivity = 'set_connectivity',
  CardDragStart = 'card_drag_start',
  CardDragEnd = 'card_drag_end',
  TableDropZoneCardEnter = 'table_drop_zone_card_enter',
  TableDropZoneCardDrop = 'table_drop_zone_card_drop',
  TableDropZoneCardLeave = 'table_drop_zone_card_leave',
  SkillClick = 'skill_click',
  SetIntercative = 'set_intercative',
  SetProfileTexture = 'set_profile_texture',
  // these events must be handled only in game
  OuterCardStateChange = 'card_state_change',
  OuterCardPlay = 'outer_card_play',
  OuterInteract = 'outer_interact',
  OuterSkillPlay = 'outer_skill_play',
  OuterSkillClick = 'outer_skill_clicked',
  OuterSkillPlayed = 'outer_skill_played',
  OuterCardDraw = 'outer_card_draw',
  OuterReady = 'outer_ready',
  OuterCardPlayed = 'outer_card_played',
  OuterSkillPlayCancel = 'outer_skill_play_cancel',
  OuterSkipTurn = 'outer_skip_turn',
}
