import { CANVAS, Scale } from 'phaser';
import { PhaserEase } from './phaser';

export type OpponentDimension = {
  x: number;
  y: number;
  angle: number;
  tooltipTransform?: { x?: number; y?: number; rotate?: number };
};

export enum OpponentSlot {
  TopCenter = 'top_center',
  TopCenterSmall = 'top_center_small',
  TopLeft = 'top_left',
  TopLeftSmall = 'top_left_small',
  TopRight = 'top_right',
  TopRightSmall = 'top_right_small',
  RightCenter = 'right_center',
  RightTop = 'right_top',
  RightBottom = 'right_bottom',
}

export const PwsmGameConstants = {
  BackgroundColor: 0x212121,
  Misc: {
    ResizeDebounceMs: 200,
    ScaleTween: 1.5,
    ScaleTweenEase: PhaserEase.EaseInOut,
    FpsMeterSelector: '#fps-meter',
  },
  PhaserConfig: {
    scale: {
      mode: Scale.ScaleModes.NONE,
      autoCenter: Scale.Center.CENTER_BOTH,
    },
    banner: false,
    type: CANVAS,
    autoFocus: true,
    render: {
      antialias: true,
      powerPreference: 'high-performance',
    },
  },
  Rendering: {
    MaxDpr: 2,
  },
  Colors: {
    Red: 0xff0000,
    LightRed: 0xee7575,
    Pink: 0xff97ee,
    Purple: 0xd34dff,
    White: 0xffffff,
    Black: 0xffffff,
    SkyBlue: 0xebefff,
    LightGrey: 0xf1f1f1,
    Grey: 0xc4c4c4,
    DarkGrey: 0x4b4b4b,
    LightYellow: 0xfff8dc,
  },
  Card: {
    AspectRatio: 2 / 3,
    Width: 720,
    Height: 1080,
    ImageWidth: 633,
    ImageHeight: 691,
    ImageOffsetTop: 27,
    ImageOffsetLeft: 44,
    ElementIconWidth: 120,
    ElementIconHeight: 120,
    ElementIconOffsetTop: 25,
    ElementIconOffsetLeft: 122,
    ValueWidth: 120,
    ValueHeight: 120,
    ValueOffsetTop: 25,
    ValueOffsetLeft: 37,
    ValueFontSize: 100,
    TitleFontSize: 80,
    TextWidth: 606,
    TextOffsetLeft: 56,
    TitleHeight: 290,
    TitleOffsetTop: 734,
    SmallTitleHeight: 86,
    SmallTitleFontSize: 68,
    SmallTitleOffsetTop: 764,
    TextFontSize: 42,
    TextHeight: 174,
    TextOffsetTop: 850,
    EffectWidth: 270,
    EffectHeight: 105,
    EffectIconSize: 58,
    EffectIconOffsetTop: 23.5,
    EffectIconOffsetLeft: 23,
    EffectOffsetTop: 162,
    EffectFontSize: 28,
    EffectTextWidth: 135,
    EffectTextHeight: 40,
    EffectTextOffsetTop: 30,
    EffectTextOffsetLeft: 94,
    OutlineWidth: 20,
    HighlightAlpha: 0.5,
    HighlightDuration: 400,
    HighlightEase: PhaserEase.EaseInOut,
    InteractionOverlayTweenAlphaMin: 0.25,
    InteractionOverlayTweenAlphaMax: 0.4,
    InteractionOverlayTweenEase: PhaserEase.Linear,
    InteractionOverlayTweenDuration: 600,
    InteractionOverlayTweenDelay: 400,
  },
  Table: {
    Width: 1920,
    Height: 1080,
    ArenaScaleInDuration: 3000,
    ArenaScaleInEase: PhaserEase.EaseOut,
    ArenaFadeInDuration: 1000,
    ArenaFadeInEase: PhaserEase.Linear,
    ArenaScaleInStartValue: 0.5,
    DiscardPileHeight: 432,
    DiscardPileWidth: 288,
    DiscardCardCount: 5,
    DiscardPileDeltaX: 80,
    DiscardPileDeltaY: 20,
    DiscardPileDeltaRotation: 10,
    DiscardPileX: 0,
    DiscardPileY: -50,
    DiscardPilePortraitX: 70,
    DiscardPilePortraitY: -50,
    DeckHeight: 360,
    DeckWidth: 240,
    DeckOffsetFactor: 1,
    DeckX: -480,
    DeckY: -50,
    DeckPortraitX: -280,
    DeckPortraitY: -50,
    DeckCardPerVisualCard: 4,
    DeckCardOffset: -3,
    DeckSilhouetteOffset: 10,
    DeckHighlightWidth: 360,
    DeckHighlightHeight: 540,
    DeckTopCardGlowWidth: 240,
    DeckTopCardGlowHeight: 360,
    DeckGlowTweenAlpha: 0.75,
    DeckGlowTweenEase: PhaserEase.EaseInOut,
    DeckGlowTweenDuration: 2000,
    DeckCursor: 'pointer',
    DeckHighlightAlpha: 0.25,
    DeckTooltipX: 240,
    DeckTooltipConfig: {
      fontSize: 40,
      backgroundColor: 'rgba(0,0,0,0.75)',
      padding: { x: 20, y: 20 },
      wordWrap: { width: 1200 },
    },
    HighlightAreaDisabledAlpha: 0,
    HighlightAreaMaxAlpha: 0.7,
    HighlightAreaMediumAlpha: 0.4,
    HighlightAreaAlphaTweenDuration: 300,
    DropZoneSize: 0.7,
    CameraShakeOnPlayDuration: 100,
    CameraShakeOnPlayDelay: 250,
    CameraShakeOnPlayIntensity: 0.005,
    DiscardPileDustParticlesConfig: {
      frame: ['black', 'grey', 'white'],
      lifespan: 700,
      speed: { min: 200, max: 1000 },
      scale: { start: 0.5, end: 1.2, random: true },
      alpha: { start: 0.8, end: 0, random: true },
      quantity: 100,
      emitting: false,
    },
    DiscardPileCardPlayDuration: 400,
    DiscardPileCardPlayDelay: 40,
    DiscardPileCardPlayEase: PhaserEase.BounceOut,
    DiscardPileDustEmitDelay: 100,
    DiscardPileDustEmitThrottle: 1000,
    DiscardPileShakeCameraThrottle: 1000,
  },
  Player: {
    FanWidth: 0.7,
    TooltipTransform: { rotate: 0, x: 0, y: -1.4 },
    FanPortraitWidth: 0.95,
    FanVerticalOffset: 15,
    PanelWidth: 0.25,
    X: 0.5,
    Y: 0.95,
    CardDrawIndicatorFontSize: 100,
  },
  Fan: {
    Width: 1200,
    AspectRatio: 5 / 1,
    CompactAspectRatio: 5 / 2,
    RotateFactor: 10,
    VerticalPushFactor: -0.15,
    HoverHorizontalPushFactor: 0.35,
    HoverVerticalPushFactor: -0.25,
    HoverScaleFactor: 1.5,
    DragScaleFactor: 2.5,
    CardTweenDuration: 300,
    CardTweenEase: PhaserEase.EaseOut,
    DiscardCardTweenDuration: 300,
    DragLockDelay: 200,
    AdditionalVerticalPushThreshold: 3,
    AdditionalVerticalPushFactor: -0.05,
    DiscardCardTweenScale: 2,
    DiscardCardTweenEase: PhaserEase.EaseOut,
    CardDrawIndicatorTransformY: -200,
  },
  Profile: {
    Width: 720,
    AspectRatio: 3 / 1,
    ActiveTweenDuration: 1000,
    ActiveTweenEase: PhaserEase.EaseInOut,
    ActiveTweenScale: 1.1,
    ActiveTweenHighlightAlpha: 0.25,
  },
  PlayerPanel: {
    Width: 1200,
    AspectRatio: 5 / 1,
    BackgroundCenterWidth: 900,
    BackgroundCenterAspectRatio: 611 / 84,
    BackgroundSideWidth: 220,
    BackgroundSideAspectRatio: 149 / 145,
    BackgroundTopSideVerticalOffset: -0.25,
    BackgroundBottomSideVerticalOffset: 0.25,
    SkillWidth: 220,
    SkillAspectRatio: 1,
    SkillDarkenAlpha: 0.5,
    SkillTweenDuration: 400,
    SkillTweenEase: PhaserEase.EaseInOut,
    SkillParticlesConfig: {
      frame: ['purple', 'blue'],
      lifespan: 700,
      speed: { min: 100, max: 800 },
      scale: { start: 0.2, end: 0.5 },
      alpha: { start: 1, end: 0 },
      rotate: { start: 0, end: 360 },
      blendMode: 'ADD',
      quantity: 400,
      emitting: false,
    },
    HighlightAlpha: 0.25,
    SkillOutlineWidth: 20,
    SkillCooldownVerticalOffset: -15,
    SkillCooldownFontSize: 80,
    CooldownGemWidth: 80,
    CooldownGemAspectRatio: 275 / 388,
    PlaceholderWidth: 0.75,
    SkillCooldownTweenDuration: 400,
    SkillCooldownTweenScale: 0.5,
    SkillCooldownTweenEase: PhaserEase.EaseInOut,
    TooltipConfig: {
      fontSize: 65,
      backgroundColor: 'rgba(0,0,0,0.75)',
      padding: { x: 20, y: 20 },
      wordWrap: { width: 1200 },
    },
  },
  Opponents: {
    Width: 1200,
    AspectRatio: 10 / 3,
    PanelWidth: 0.8,
    HighlightAlpha: 0.75,
    HighlightExpand: 1.5,
    DisconnectedAlpha: 0.5,
    CardDrawIndicatorFontSize: 200,
    Sizes: {
      1: 0.35,
      2: 0.3,
      3: 0.275,
      4: 0.2,
      5: 0.2,
    },
    TooltipScales: {
      1: 1,
      2: 1,
      3: 1.5,
      4: 2,
      5: 2,
    },
    Slots: {
      1: [OpponentSlot.TopCenter],
      2: [OpponentSlot.TopLeft, OpponentSlot.TopRight],
      3: [OpponentSlot.TopLeft, OpponentSlot.TopRight, OpponentSlot.RightCenter],
      4: [OpponentSlot.TopLeft, OpponentSlot.TopRight, OpponentSlot.RightTop, OpponentSlot.RightBottom],
      5: [
        OpponentSlot.TopLeftSmall,
        OpponentSlot.TopCenterSmall,
        OpponentSlot.TopRightSmall,
        OpponentSlot.RightTop,
        OpponentSlot.RightBottom,
      ],
    },
    SlotsPortrait: {
      1: [OpponentSlot.TopCenter],
      2: [OpponentSlot.TopCenter, OpponentSlot.RightCenter],
      3: [OpponentSlot.TopCenter, OpponentSlot.RightTop, OpponentSlot.RightBottom],
      4: [OpponentSlot.TopLeftSmall, OpponentSlot.TopLeftSmall, OpponentSlot.RightTop, OpponentSlot.RightBottom],
      5: [
        OpponentSlot.TopLeft,
        OpponentSlot.TopRight,
        OpponentSlot.RightTop,
        OpponentSlot.RightCenter,
        OpponentSlot.RightBottom,
      ],
    },
    Dimensions: {
      [OpponentSlot.TopCenter]: { x: 0.5, y: 0.04, angle: 0, tooltipTransform: { y: 2 } },
      [OpponentSlot.TopCenterSmall]: { x: 0.5, y: 0.07, angle: 0, tooltipTransform: { y: 3 } },
      [OpponentSlot.TopLeft]: { x: 0.3, y: 0.07, angle: 0, tooltipTransform: { y: 3 } },
      [OpponentSlot.TopLeftSmall]: { x: 0.25, y: 0.07, angle: 0, tooltipTransform: { y: 3 } },
      [OpponentSlot.TopRight]: { x: 0.75, y: 0.07, angle: 0, tooltipTransform: { y: 3, x: -4 } },
      [OpponentSlot.TopRightSmall]: { x: 0.7, y: 0.07, angle: 0, tooltipTransform: { y: 3, x: -2 } },
      [OpponentSlot.RightCenter]: { x: 0.95, y: 0.45, angle: 90, tooltipTransform: { rotate: -90, y: 6, x: -1 } },
      [OpponentSlot.RightTop]: { x: 0.95, y: 0.25, angle: 90, tooltipTransform: { rotate: -90, y: 6, x: -1 } },
      [OpponentSlot.RightBottom]: { x: 0.95, y: 0.65, angle: 90, tooltipTransform: { rotate: -90, y: 6, x: -3 } },
    } as Record<OpponentSlot, OpponentDimension>,
  },
  GameObjectName: {
    TableDropZone: 'table_drop_zone',
  },
  SkillRenderer: {
    AlphaTweenDuration: 300,
    SkillParticlesEmitterConfig: {
      frequency: 10,
      emitting: true,
      alpha: { start: 0, end: 0.5 },
      lifespan: 1000,
      quantity: 1,
      scale: { start: 0.01, end: 0.02 },
      speed: 1000,
    },
    SkillParticlesEmitterTweenDuration: 10000,
    SkillParticlesEmitterTweenEase: PhaserEase.Linear,
    CameraShakeOnSkillDuration: 100,
    CameraShakeOnSkillIntensity: 0.01,
  },
  Timer: {
    Width: 200,
    AspectRatio: 1,
    SceneSize: 0.03,
    ArcWidth: 12,
    ArcAlpha: 1,
    ArcStartAngle: -90,
    ArcRadius: 80,
    TweenDuration: 1800,
    HighlightAlpha: 0.15,
    HighlightScale: 0.1,
    HighlightTweenDuration: 1500,
    HighlightTweenEase: PhaserEase.Linear,
    TweenEase: PhaserEase.Elastic,
    FontSize: 100,
    TweenParams: [1, 1],
    ParticlesEmitterConfig: {
      frequency: 10,
      emitting: true,
      alpha: { start: 1, end: 0 },
      lifespan: 300,
      quantity: 1,
      scale: { start: 0.05, end: 0.01 },
      speed: 700,
    },
  },
  DrawRenderer: {
    DirectionMaxCards: 5,
    Delay: 100,
    Duration: 500,
    AlphaUpThreshold: 0.4,
    AlphaDownThreshold: 0.6,
    Rotation: 90,
    CardScale: 0.2,
    Ease: PhaserEase.EaseOut,
  },
  InteractionRenderer: {
    CardParticlesEmitterOffsetY: -50,
    ParticlesRayConfig: {
      frame: ['white'],
      lifespan: 1000,
      speed: { min: 500, max: 750 },
      scale: { start: 0, end: 0.3 },
      alpha: { values: [0, 0, 0.5, 0] },
      rotate: { start: 0, end: 180 },
      blendMode: 'ADD',
      quantity: 1,
      emitting: true,
    },
    ParticlesConfig: {
      frame: ['white'],
      lifespan: 1000,
      speed: 200,
      scale: { start: 0.5, end: 0.2 },
      alpha: { values: [0, 0, 0, 0.5, 0] },
      rotate: { start: 0, end: 180 },
      blendMode: 'ADD',
      quantity: 10,
      emitting: true,
    },
    ParticlesAnglesDelta: 3,
  },
  CardDrawIndicator: {
    Color: '#FF0000',
    TweenDuration: 5000,
    TweenEase: PhaserEase.EaseOut,
    Stroke: '#000000',
    StrokeWidth: 0.1,
    TransformX: -0.05,
    TransformY: -0.5,
  },
  Tooltip: {
    TweenDuration: 500,
    TweenEase: PhaserEase.Linear,
  },
  FontFamily: 'Piazzolla',
  TextShadow: { fill: true, blur: 12, color: 'rgba(0, 0, 0, 0.9)' },
};
