import { ActiveSkillItemKey } from '@/game-data';
import { CardElement, CardId } from '@/game-data/card';

export const Resource = {
  Placeholder: 'placeholder',
  Misc: {
    HighlightWhite: 'misc/highlight_white',
  },
  Particle: {
    BaseCircle: 'particle/base_circle',
    BaseSquare: 'particle/base_square',
    Dust: 'particle/dust',
    Flare: 'particle/flare',
  },
  GameTable: {
    DeckTexture: 'game_table/deck_texture',
    HighlightArea: 'game_table/highlight_area',
    DeckBottom: 'game_table/deck_bottom',
    Arena: {
      Standard: {
        Background: 'game_table/arena/standard/background',
        Table: 'game_table/arena/standard/table',
      },
      FlowerField: {
        Background: 'game_table/arena/flower_field/background',
        Table: 'game_table/arena/flower_field/table',
      },
      LoneMountain: {
        Background: 'game_table/arena/lone_mountain/background',
        Table: 'game_table/arena/lone_mountain/table',
      },
      Library: {
        Background: 'game_table/arena/library/background',
        Table: 'game_table/arena/library/table',
      },
      Lab: {
        Background: 'game_table/arena/lab/background',
        Table: 'game_table/arena/lab/table',
      },
    },
  },
  PlayerPanel: {
    BackgroundCenter: 'player_panel/background_center',
    BackgroundSide: 'player_panel/background_side',
    SkillFrame: 'player_panel/skill_frame',
    SkillCooldownBackground: 'player_panel/skill_cooldown_background',
    SkillSilhouetteWhite: 'player_panel/skill_silhouette_white',
    SkillSilhouetteBlack: 'player_panel/skill_silhouette_black',
    Profile: 'player_panel/profile',
    DefaultProfile: 'player_panel/default_profile',
    PanelPlaceholder: 'player_panel/panel_placeholder',
  },
  Skill: {
    [ActiveSkillItemKey.ReduceStartCards]: 'skill/reduce_start_cards',
    [ActiveSkillItemKey.SelectedPlayerDrawsCards]: 'skill/selected_player_draws_cards',
    [ActiveSkillItemKey.TransformOwnCardIntoMultidog]: 'skill/transorm_own_card_into_multidog',
    [ActiveSkillItemKey.ReplaceOwnHand]: 'skill/replace_own_hand',
    [ActiveSkillItemKey.SelectedPlayerBurnsCards]: 'skill/selected_player_burns_cards',
    [ActiveSkillItemKey.PlayAnyCard]: 'skill/play_any_card',
    [ActiveSkillItemKey.TransformRandomOpponentsCardIntoSelected]:
      'skill/transform_random_opponents_card_into_selected',
    [ActiveSkillItemKey.DiscardRandomCards]: 'skill/discard_random_cards',
  },
  SkillRenderer: {
    Background: 'skill_renderer/background',
  },
  Timer: {
    Background: 'timer/background',
  },
  Card: {
    Silhouette: 'card/silhouette',
    BackSilhouette: 'card/back_silhouette',
    BackGlow: 'card/back_glow',
    Back: {
      Arcane: 'card/back/arcane',
      Nature: 'card/back/nature',
      Filth: 'card/back/filth',
      Standard: 'card/back/standard',
      Fury: 'card/back/fury',
      Bloom: 'card/back/bloom',
    },
    Stone: {
      [CardElement.Arcane]: 'card/stone/arcane',
      [CardElement.Nature]: 'card/stone/nature',
      [CardElement.Filth]: 'card/stone/filth',
      [CardElement.Multimatter]: 'card/stone/multimatter',
    },
    ElementIcon: {
      [CardElement.Arcane]: 'card/element_icon/arcane',
      [CardElement.Nature]: 'card/element_icon/nature',
      [CardElement.Filth]: 'card/element_icon/filth',
      [CardElement.Multimatter]: 'card/element_icon/multimatter',
    },
    Value: {
      Hydrant: 'card/value/hydrant',
      Soundboard: 'card/value/soundboard',
      Multimatter: 'card/value/multimatter',
      BallOfFortune: 'card/value/ball_of_fortune',
      TrashCanDiving: 'card/value/trash_can_diving',
      TreatHiding: 'card/value/treat_hiding',
      Shaking: 'card/value/shaking',
    },
    Skin: {
      Standard: 'card/skin/standard',
      Golden: 'card/skin/golden',
    },
    Effect: {
      BackgroundExpanded: 'card/effect/background_expanded',
      BackgroundContracted: 'card/effect/background_contracted',
      Transform: 'card/effect/transform',
      Burn: 'card/effect/burn',
      Curse: 'card/effect/curse',
    },
    Interaction: {
      Overlay1: 'card/interaction/overlay1',
      Overlay2: 'card/interaction/overlay2',
      Overlay3: 'card/interaction/overlay3',
    },
    Image: {
      [CardId.Arcane1]: 'card/image/arcane_1',
      [CardId.Arcane2]: 'card/image/arcane_2',
      [CardId.Arcane3]: 'card/image/arcane_3',
      [CardId.Arcane4]: 'card/image/arcane_4',
      [CardId.Arcane5]: 'card/image/arcane_5',
      [CardId.Arcane6]: 'card/image/arcane_6',
      [CardId.Arcane7]: 'card/image/arcane_7',
      [CardId.Arcane8]: 'card/image/arcane_8',
      [CardId.Arcane9]: 'card/image/arcane_9',
      [CardId.ArcaneHydrant]: 'card/image/arcane_hydrant',
      [CardId.ArcaneShaking]: 'card/image/arcane_shaking',
      // [CardId.ArcaneSoundboard]: 'card/image/arcane_soundboard',
      [CardId.ArcaneTrashCanDiving]: 'card/image/arcane_trash_can_diving',
      [CardId.ArcaneTreatHiding]: 'card/image/arcane_treat_hiding',

      [CardId.Nature1]: 'card/image/nature_1',
      [CardId.Nature2]: 'card/image/nature_2',
      [CardId.Nature3]: 'card/image/nature_3',
      [CardId.Nature4]: 'card/image/nature_4',
      [CardId.Nature5]: 'card/image/nature_5',
      [CardId.Nature6]: 'card/image/nature_6',
      [CardId.Nature7]: 'card/image/nature_7',
      [CardId.Nature8]: 'card/image/nature_8',
      [CardId.Nature9]: 'card/image/nature_9',
      [CardId.NatureHydrant]: 'card/image/nature_hydrant',
      [CardId.NatureShaking]: 'card/image/nature_shaking',
      // [CardId.NatureSoundboard]: 'card/image/nature_soundboard',
      [CardId.NatureTrashCanDiving]: 'card/image/nature_trash_can_diving',
      [CardId.NatureTreatHiding]: 'card/image/nature_treat_hiding',

      [CardId.Filth1]: 'card/image/filth_1',
      [CardId.Filth2]: 'card/image/filth_2',
      [CardId.Filth3]: 'card/image/filth_3',
      [CardId.Filth4]: 'card/image/filth_4',
      [CardId.Filth5]: 'card/image/filth_5',
      [CardId.Filth6]: 'card/image/filth_6',
      [CardId.Filth7]: 'card/image/filth_7',
      [CardId.Filth8]: 'card/image/filth_8',
      [CardId.Filth9]: 'card/image/filth_9',
      [CardId.FilthHydrant]: 'card/image/filth_hydrant',
      [CardId.FilthShaking]: 'card/image/filth_shaking',
      // [CardId.FilthSoundboard]: 'card/image/filth_soundboard',
      [CardId.FilthTrashCanDiving]: 'card/image/filth_trash_can_diving',
      [CardId.FilthTreatHiding]: 'card/image/filth_treat_hiding',

      [CardId.Multimatter]: 'card/image/multimatter',
      [CardId.BallOfFortune]: 'card/image/ball_of_fortune',
      [CardId.BallOfCurse]: 'card/image/ball_of_curse',
      [CardId.BallOfFate]: 'card/image/ball_of_fate',
      [CardId.BallOfLuck]: 'card/image/ball_of_luck',
      [CardId.BallOfWisdom]: 'card/image/ball_of_wisdom',
      [CardId.BallOfWish]: 'card/image/ball_of_wish',
    },
  },
};
