export enum RouteName {
  Main = 'main',
  Game = 'game',
  Lobby = 'lobby',
  Atlas = 'atlas',
  Journal = 'journal',
  Shop = 'shop',
  QuickMatch = 'quick-match',
  RankedMatch = 'ranked-match',
  Play = 'play',
  Practice = 'practice',
  CardSet = 'card-set',
  Treasury = 'treasury',
  Journey = 'journey',
  SkillTree = 'skill-tree',
  EssenceMultipliers = 'essence-multipliers',
  Equipment = 'equipment',
  SetupProfile = 'setup-profile',
  Auth = 'auth',
  Loading = 'loading',
  Tutorial = 'tutorial',
}
