import { CardId } from './card/card-id';
import { ItemKey, type CardSkinItemKey } from './item-key';

export enum CardSkin {
  Standard = 'standard',
  Golden = 'golden',
}

export const CardSkinItemKeyToCardSkin: Record<CardSkinItemKey, CardSkin> = {
  [ItemKey.CardSkinGoldenSpecial]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenLabradoodle]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenDobermann]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenHusky]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenRetriever]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenCorgi]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenPug]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenDoxie]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenYork]: CardSkin.Golden,
  [ItemKey.CardSkinGoldenSpitz]: CardSkin.Golden,
};

export const CardIdToCardSkinItemKey: { [id in CardId]?: CardSkinItemKey[] } = {
  [CardId.Nature1]: [ItemKey.CardSkinGoldenSpitz],
  [CardId.Nature2]: [ItemKey.CardSkinGoldenYork],
  [CardId.Nature3]: [ItemKey.CardSkinGoldenDoxie],
  [CardId.Nature4]: [ItemKey.CardSkinGoldenPug],
  [CardId.Nature5]: [ItemKey.CardSkinGoldenCorgi],
  [CardId.Nature6]: [ItemKey.CardSkinGoldenRetriever],
  [CardId.Nature7]: [ItemKey.CardSkinGoldenHusky],
  [CardId.Nature8]: [ItemKey.CardSkinGoldenDobermann],
  [CardId.Nature9]: [ItemKey.CardSkinGoldenLabradoodle],
  [CardId.NatureHydrant]: [ItemKey.CardSkinGoldenSpecial],
  // [CardId.NatureSoundboard]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.NatureTrashCanDiving]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.NatureShaking]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.NatureTreatHiding]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.Filth1]: [ItemKey.CardSkinGoldenSpitz],
  [CardId.Filth2]: [ItemKey.CardSkinGoldenYork],
  [CardId.Filth3]: [ItemKey.CardSkinGoldenDoxie],
  [CardId.Filth4]: [ItemKey.CardSkinGoldenPug],
  [CardId.Filth5]: [ItemKey.CardSkinGoldenCorgi],
  [CardId.Filth6]: [ItemKey.CardSkinGoldenRetriever],
  [CardId.Filth7]: [ItemKey.CardSkinGoldenHusky],
  [CardId.Filth8]: [ItemKey.CardSkinGoldenDobermann],
  [CardId.Filth9]: [ItemKey.CardSkinGoldenLabradoodle],
  [CardId.FilthHydrant]: [ItemKey.CardSkinGoldenSpecial],
  // [CardId.FilthSoundboard]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.FilthTrashCanDiving]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.FilthShaking]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.FilthTreatHiding]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.Arcane1]: [ItemKey.CardSkinGoldenSpitz],
  [CardId.Arcane2]: [ItemKey.CardSkinGoldenYork],
  [CardId.Arcane3]: [ItemKey.CardSkinGoldenDoxie],
  [CardId.Arcane4]: [ItemKey.CardSkinGoldenPug],
  [CardId.Arcane5]: [ItemKey.CardSkinGoldenCorgi],
  [CardId.Arcane6]: [ItemKey.CardSkinGoldenRetriever],
  [CardId.Arcane7]: [ItemKey.CardSkinGoldenHusky],
  [CardId.Arcane8]: [ItemKey.CardSkinGoldenDobermann],
  [CardId.Arcane9]: [ItemKey.CardSkinGoldenLabradoodle],
  [CardId.ArcaneHydrant]: [ItemKey.CardSkinGoldenSpecial],
  // [CardId.ArcaneSoundboard]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.ArcaneTrashCanDiving]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.ArcaneShaking]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.ArcaneTreatHiding]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.Multimatter]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfFortune]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfFate]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfCurse]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfLuck]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfWisdom]: [ItemKey.CardSkinGoldenSpecial],
  [CardId.BallOfWish]: [ItemKey.CardSkinGoldenSpecial],
};

export const ItemToCardId: Record<CardSkinItemKey, CardId[]> = {
  [ItemKey.CardSkinGoldenLabradoodle]: [CardId.Filth9, CardId.Arcane9, CardId.Nature9],
  [ItemKey.CardSkinGoldenDobermann]: [CardId.Filth8, CardId.Arcane8, CardId.Nature8],
  [ItemKey.CardSkinGoldenHusky]: [CardId.Filth7, CardId.Arcane7, CardId.Nature7],
  [ItemKey.CardSkinGoldenRetriever]: [CardId.Filth6, CardId.Arcane6, CardId.Nature6],
  [ItemKey.CardSkinGoldenCorgi]: [CardId.Filth5, CardId.Arcane5, CardId.Nature5],
  [ItemKey.CardSkinGoldenPug]: [CardId.Filth4, CardId.Arcane4, CardId.Nature4],
  [ItemKey.CardSkinGoldenDoxie]: [CardId.Filth3, CardId.Arcane3, CardId.Nature3],
  [ItemKey.CardSkinGoldenYork]: [CardId.Filth2, CardId.Arcane2, CardId.Nature2],
  [ItemKey.CardSkinGoldenSpitz]: [CardId.Filth1, CardId.Arcane1, CardId.Nature1],
  [ItemKey.CardSkinGoldenSpecial]: [
    CardId.FilthShaking,
    CardId.FilthHydrant,
    CardId.FilthTrashCanDiving,
    CardId.FilthTreatHiding,
    CardId.ArcaneShaking,
    CardId.ArcaneHydrant,
    CardId.ArcaneTrashCanDiving,
    CardId.ArcaneTreatHiding,
    CardId.NatureShaking,
    CardId.NatureHydrant,
    CardId.NatureTrashCanDiving,
    CardId.NatureTreatHiding,
  ],
};
