export enum CardId {
  // SERVICE CARDS

  Placeholder = 'placeholder',

  // STANDARD SET

  Nature1 = 'nature_1',
  Nature2 = 'nature_2',
  Nature3 = 'nature_3',
  Nature4 = 'nature_4',
  Nature5 = 'nature_5',
  Nature6 = 'nature_6',
  Nature7 = 'nature_7',
  Nature8 = 'nature_8',
  Nature9 = 'nature_9',
  NatureHydrant = 'nature_hydrant',
  // NatureSoundboard = 'nature_soundboard',
  NatureTrashCanDiving = 'nature_trash_can_diving',
  NatureShaking = 'nature_shaking',
  NatureTreatHiding = 'nature_treat_hiding',

  Filth1 = 'filth_1',
  Filth2 = 'filth_2',
  Filth3 = 'filth_3',
  Filth4 = 'filth_4',
  Filth5 = 'filth_5',
  Filth6 = 'filth_6',
  Filth7 = 'filth_7',
  Filth8 = 'filth_8',
  Filth9 = 'filth_9',
  FilthHydrant = 'filth_hydrant',
  // FilthSoundboard = 'filth_soundboard',
  FilthTrashCanDiving = 'filth_trash_can_diving',
  FilthShaking = 'filth_shaking',
  FilthTreatHiding = 'filth_treat_hiding',

  Arcane1 = 'arcane_1',
  Arcane2 = 'arcane_2',
  Arcane3 = 'arcane_3',
  Arcane4 = 'arcane_4',
  Arcane5 = 'arcane_5',
  Arcane6 = 'arcane_6',
  Arcane7 = 'arcane_7',
  Arcane8 = 'arcane_8',
  Arcane9 = 'arcane_9',
  ArcaneHydrant = 'arcane_hydrant',
  // ArcaneSoundboard = 'arcane_soundboard',
  ArcaneTrashCanDiving = 'arcane_trash_can_diving',
  ArcaneShaking = 'arcane_shaking',
  ArcaneTreatHiding = 'arcane_treat_hiding',

  Multimatter = 'multimatter',
  BallOfFortune = 'ball_of_fortune',
  BallOfFate = 'ball_of_fate',
  BallOfCurse = 'ball_of_curse',
  BallOfLuck = 'ball_of_luck',
  BallOfWisdom = 'ball_of_wisdom',
  BallOfWish = 'ball_of_wish',
}
