import { Module } from '@kwokka/common-node';
import {
  AccessRightRepository,
  AccessRoleRepository,
  AccountRepository,
  AccountRolesRepository,
  AccountTypeRolesRepository,
  CreateAccessRightUsecase,
  CreateAccessRoleUsecase,
  CreateAccountRolesUsecase,
  CreateAccountTypeRolesUsecase,
  CreateAccountUsecase,
  CreateCredentialUsecase,
  CredentialRepository,
  DeleteAccessRightUsecase,
  DeleteAccessRoleUsecase,
  DeleteAccountRolesUsecase,
  DeleteAccountTypeRolesUsecase,
  DeleteAccountUsecase,
  DeleteCredentialUsecase,
  GetAccessRightByIdUsecase,
  GetAccessRightsForAccountUsecase,
  GetAccessRoleByIdUsecase,
  GetAccountByIdUsecase,
  GetAccountRolesByAccountIdUsecase,
  GetAccountRolesByIdUsecase,
  GetAccountTypeRolesByIdUsecase,
  GetCredentialByIdentifierUsecase,
  GetCredentialByIdUsecase,
  GetTokenByIdUsecase,
  IssueRestoreTokenUsecase,
  IssueTokenPairUsecase,
  IssueVerifyTokenUsecase,
  ListAccessRightsUsecase,
  ListAccessRolesUsecase,
  ListAccountRolesUsecase,
  ListAccountsUsecase,
  ListAccountTypeRolesUsecase,
  ListCredentialsByAccountIdUsecase,
  ListCredentialsUsecase,
  ListTokensByAccountIdUsecase,
  ListTokensUsecase,
  RefreshAccessUsecase,
  RevokeAccessByAccountIdUsecase,
  RevokeAccessByCorrelationIdUsecase,
  RevokeTokenByIdUsecase,
  SetAccountActiveUsecase,
  SetAccountVerifiedUsecase,
  TokenRepository,
  UpdateAccessRightUsecase,
  UpdateAccessRoleUsecase,
  UpdateAccountRolesUsecase,
  UpdateAccountTypeRolesUsecase,
  UpdateCredentialUsecase,
} from '../usecase';
import {
  AccessRightMongoRepository,
  AccessRoleMongoRepository,
  AccountMongoRepository,
  TokenMongoRepository,
  AccountRolesMongoRepository,
  AccountTypeRolesMongoRepository,
  CredentialMongoRepository,
  AccessRightV1Controller,
  AccessRoleV1Controller,
  AccountRolesV1Controller,
  AccountTypeRolesV1Controller,
  CredentialV1Controller,
  AccountV1Controller,
  TokenV1Controller,
  OnboardingV1Controller,
  RootRouter,
  V1RootRouter,
  AccessRightV1Router,
  AccessRoleV1Router,
  AccountRolesV1Router,
  AccountTypeRolesV1Router,
  AccountV1Router,
  CredentialV1Router,
  TokenV1Router,
  OnboardingV1Router,
  GoogleOauth2Service,
  DiscordOauth2Service,
  HCaptchaService,
  CaptchaService,
  CaptchaMiddleware,
} from '../application';

export class OwlModule extends Module {
  public get components() {
    return [
      // usecase/ports
      { identifier: AccessRightRepository, implementer: AccessRightMongoRepository },
      { identifier: AccessRoleRepository, implementer: AccessRoleMongoRepository },
      { identifier: AccountRepository, implementer: AccountMongoRepository },
      { identifier: TokenRepository, implementer: TokenMongoRepository },
      { identifier: AccountRolesRepository, implementer: AccountRolesMongoRepository },
      { identifier: AccountTypeRolesRepository, implementer: AccountTypeRolesMongoRepository },
      { identifier: CredentialRepository, implementer: CredentialMongoRepository },

      // usecase/access-right
      GetAccessRightByIdUsecase,
      ListAccessRightsUsecase,
      CreateAccessRightUsecase,
      UpdateAccessRightUsecase,
      DeleteAccessRightUsecase,
      GetAccessRightsForAccountUsecase,

      // usecase/access-role
      GetAccessRoleByIdUsecase,
      ListAccessRolesUsecase,
      CreateAccessRoleUsecase,
      UpdateAccessRoleUsecase,
      DeleteAccessRoleUsecase,

      // usecase/account-roles
      GetAccountRolesByIdUsecase,
      ListAccountRolesUsecase,
      CreateAccountRolesUsecase,
      UpdateAccountRolesUsecase,
      DeleteAccountRolesUsecase,
      GetAccountRolesByAccountIdUsecase,

      // usecase/account-type-roles
      GetAccountTypeRolesByIdUsecase,
      ListAccountTypeRolesUsecase,
      CreateAccountTypeRolesUsecase,
      UpdateAccountTypeRolesUsecase,
      DeleteAccountTypeRolesUsecase,

      // usecase/account
      GetAccountByIdUsecase,
      ListAccountsUsecase,
      CreateAccountUsecase,
      SetAccountActiveUsecase,
      SetAccountVerifiedUsecase,
      DeleteAccountUsecase,

      // usecase/credential
      GetCredentialByIdUsecase,
      ListCredentialsUsecase,
      ListCredentialsByAccountIdUsecase,
      CreateCredentialUsecase,
      UpdateCredentialUsecase,
      DeleteCredentialUsecase,
      GetCredentialByIdentifierUsecase,

      // usecase/token
      GetTokenByIdUsecase,
      ListTokensUsecase,
      ListTokensByAccountIdUsecase,
      RevokeAccessByAccountIdUsecase,
      RevokeAccessByCorrelationIdUsecase,
      RefreshAccessUsecase,
      IssueTokenPairUsecase,
      IssueRestoreTokenUsecase,
      RevokeTokenByIdUsecase,
      IssueVerifyTokenUsecase,

      // application/middleware
      CaptchaMiddleware,

      // application/controller
      AccessRightV1Controller,
      AccessRoleV1Controller,
      AccountRolesV1Controller,
      AccountTypeRolesV1Controller,
      CredentialV1Controller,
      AccountV1Controller,
      TokenV1Controller,
      OnboardingV1Controller,

      // application/router
      RootRouter,
      V1RootRouter,
      AccessRightV1Router,
      AccessRoleV1Router,
      AccountRolesV1Router,
      AccountTypeRolesV1Router,
      AccountV1Router,
      CredentialV1Router,
      TokenV1Router,
      OnboardingV1Router,

      // service
      GoogleOauth2Service,
      DiscordOauth2Service,
      { identifier: CaptchaService, implementer: HCaptchaService },
    ];
  }
}
